import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import { pnpPlugin } from '@yarnpkg/esbuild-plugin-pnp'

// TODO: Remove this when Obsidian ships with node 14.18+
const stripNodeColonPlugin = {
    name: 'strip-node-colon',
    setup({ onResolve, onLoad }) {
        onResolve({ filter: /^node:/ }, (args) => {
            return { path: args.path.slice('node:'.length), external: true }
        })
    },
}

const codemirrors = [
    '@codemirror/autocomplete',
    '@codemirror/closebrackets',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/comment',
    '@codemirror/fold',
    '@codemirror/gutter',
    '@codemirror/highlight',
    '@codemirror/history',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/matchbrackets',
    '@codemirror/panel',
    '@codemirror/rangeset',
    '@codemirror/rectangular-selection',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/stream-parser',
    '@codemirror/text',
    '@codemirror/tooltip',
    '@codemirror/view',
]

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/
`

const prod = process.argv[2] === 'production'

esbuild
    .build({
        banner: {
            js: banner,
        },
        plugins: [stripNodeColonPlugin, pnpPlugin()],
        entryPoints: ['src/main.ts'],
        bundle: true,
        external: ['obsidian', 'electron', ...builtins, ...codemirrors, 'node:*'],
        platform: 'node',
        format: 'cjs',
        watch: !prod,
        target: 'es2016',
        logLevel: 'info',
        loader: {
            '.pegjs': 'text',
            '.js.static': 'text',
            '.svg_content': 'text',
            '.html': 'text',
        },
        sourcemap: prod ? false : 'inline',
        treeShaking: true,
        outfile: 'main.js',
    })
    .catch(() => process.exit(1))
