name: CI Testing

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Obsidian currently uses 14.x, but will likely upgrade to 16.x soon
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '${{ matrix.node-version }}'

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run tests
      run: yarn test:ci